version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=random
    volumes:
      - pgdata:/var/lib/postgresql/data

  docker_compose_example:
    build:
      network: host
      context: ./
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:random@postgres:5432/postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes: 
  pgdata:
